// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAi9t0nt4fzu-R9yeW6gPPLexiHMH9XQU',
    appId: '1:621257764059:web:daae7ff76ec9192901f0fe',
    messagingSenderId: '621257764059',
    projectId: 'lastchance-ec817',
    authDomain: 'lastchance-ec817.firebaseapp.com',
    storageBucket: 'lastchance-ec817.appspot.com',
    measurementId: 'G-6GXV9BEKQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMn4JsYiRLuo5y6u12zNLdP7k5KbN-N0I',
    appId: '1:621257764059:android:3dd739ef19fa099801f0fe',
    messagingSenderId: '621257764059',
    projectId: 'lastchance-ec817',
    storageBucket: 'lastchance-ec817.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH87_sihvACga8sLClRu25rMrWGA-eOu8',
    appId: '1:621257764059:ios:ab7b9c94163be58201f0fe',
    messagingSenderId: '621257764059',
    projectId: 'lastchance-ec817',
    storageBucket: 'lastchance-ec817.appspot.com',
    androidClientId: '621257764059-s09uefis63asg49falsobi4gb09heefo.apps.googleusercontent.com',
    iosClientId: '621257764059-d6jfl6s3v5vopvn5lv2dveh7cuvj9tuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
